### ISSUE TITLE
Provide a means for excluding specified file(s) from being browserified

### ISSUE THREAD

**Issue by gordonwritescode** [jnordberg/wintersmith-browserify#3]
I know that we can configure Browserify to *ignore* files, but from my understanding this only ignores them when already generating a bundle. I would like for there to be a way to tell the plugin not to Browserify a file or directory of files.

For instance, let's say I have a `vendor` directory that contains a handful of external libraries that do not support CommonJS or I simply would like to include them individually (or maybe I am Uglifying them). Since the plugin registers itself for both `.js` and `.coffee` files, it Browserifies these scripts.

I propose adding a config option:

```json
{
    "browserify": {
        "exclude": [
            "/path/to/vender/directory",
            "/some/script.js",
            "/some/other/script.js"
        ]
    }
}
```

The plugin could keep track of these and if there is a matched file path, instead of Browserifying - it could delegate it the the StaticFile plugin for serving.

Right now I am having to patch the plugin to only honor `.coffee` (all but vendor libs are coffee, so this is acceptable for the time being), but would like for a more permanent solution. The problem comes from jQuery Mobile needing to be executed in `window` scope, so it can attach to `window.$`, but when Browserified, we lose this.

I don't think it is Browserify's responsibility to "fix" what's "broken" about jQuery Mobile, but we should provide a way to workaround this. 

I'd be happy to work on this and send a PR, if you would consider this a valid feature to add.

**Comment by jnordberg** [comment]
Hey, sorry for the slow response on this.

The glob is now generated based on the extensions passed in as options... But we could still add the fileGlob option that overrides that.

I don't think there is a elegant solution to this problem without redesigning the plugin system a bit. For now adding the fileGlob option for these corner cases will have to do :)

If you update your pr i'll accept it.

**Comment by collingreen** [comment]
I'll get that done tonight!

**Comment by collingreen** [comment]
This issue can probably be closed since `fileGlob` was merged into master in PR https://github.com/jnordberg/wintersmith-browserify/pull/10

**Comment by jnordberg** [comment]
Yep :+1:
